name = "Semantix AI (CDN)"
uid = "a1847e4e-1a98-7c10-f424-696ab6f99b6ab57c98ae"
type = "theme"
handle = "semantix-cdn"

[capabilities]
network_access = true
block_progress = false

[extension_points]
  # Main CDN loader block
  [[extension_points.targets]]
  target = "section"
  module = "blocks/semantix-app.liquid"